import Link from "next/link";
import { redirect } from "next/navigation";
import { Badge, Card, PageHeader } from "@/components/ui-kit";
import { requireCurrentUser } from "@/server/auth/current-user";
import { resolvePermissionCoverage } from "@/server/permissions/permission-resolver";
import { orgPermissionModuleKeys, talentAbilityKeys } from "@/server/permissions/permission-constants";
import { addTalentGradeThreshold, addTalentNineBoxRule, addTalentRatingOption, addTalentReviewDimension, createTalentReviewTemplate, initializeDefaultTalentReviewTemplate, publishTalentReviewTemplate } from "@/server/talent/review-actions";
import { getTalentReviewConfig } from "@/server/talent/review-query";
const input = "h-9 rounded-lg border border-border bg-background px-3 text-sm";
const submit = "h-9 rounded-full bg-primary px-4 text-sm text-primary-foreground";
export default async function Page() {
  const user = await requireCurrentUser(); const permission = await resolvePermissionCoverage(user, orgPermissionModuleKeys.talent, talentAbilityKeys.viewConfig); if (!permission.hasPermission) redirect("/talent");
  const data = await getTalentReviewConfig(user); const drafts = data.templates.filter((row) => row.status === "DRAFT"); const departmentName = new Map(data.departments.map((row) => [row.id, row.name]));
  const draftSelect = (name = "templateVersionId") => <select name={name} required className={input}>{drafts.map((row) => <option key={row.id} value={row.id}>{row.name} V{row.version}</option>)}</select>;
  return <Card className="!p-6"><PageHeader title="人才盘点模型配置" description="六维、评分档、等级区间和九宫格均可配置；发布后只读" action={<Link href="/talent" className="inline-flex h-9 items-center justify-center rounded-lg border border-border bg-card px-4 text-sm font-semibold transition-colors hover:bg-muted">返回人才发展</Link>}/>
    <Card className="mb-4"><form action={createTalentReviewTemplate} className="grid md:grid-cols-4 gap-2"><select name="departmentOrgNodeId" className={input}>{data.departments.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input name="name" required placeholder="模型名称" className={`${input} md:col-span-2`}/><button className={submit}>保存草稿</button><input name="description" placeholder="模型用途或版本说明（编号和初始版本由系统生成）" className={`${input} md:col-span-4`}/></form></Card>
    {drafts.length > 0 && <Card className="mb-4"><h3 className="font-semibold mb-3">自定义草稿规则</h3><div className="grid xl:grid-cols-2 gap-4"><Rule title="评价维度"><form action={addTalentReviewDimension} className="grid grid-cols-3 gap-2">{draftSelect()}<input name="name" required placeholder="维度名称" className={input}/><select name="category" className={input}><option value="VALUE">价值观</option><option value="POTENTIAL">发展潜力</option><option value="PERFORMANCE">当前绩效</option></select><input name="maxScore" type="number" min="1" step="1" required defaultValue="5" placeholder="维度满分" className={input}/><label className="text-xs flex items-center gap-2"><input name="isRequired" type="checkbox" defaultChecked/>必填</label><button className={`${submit} col-span-2`}>添加维度</button></form></Rule><Rule title="评分选项"><form action={addTalentRatingOption} className="grid grid-cols-3 gap-2">{draftSelect()}<input name="code" required placeholder="S" className={input}/><input name="label" required placeholder="杰出" className={input}/><input name="numericScore" type="number" min="1" step="1" required placeholder="等级分值，如5" className={input}/><button className={submit}>添加评分档</button></form></Rule><Rule title="总分等级区间"><form action={addTalentGradeThreshold} className="grid grid-cols-3 gap-2">{draftSelect()}<input name="gradeCode" required placeholder="S" className={input}/><input name="label" required placeholder="杰出" className={input}/><input name="minScore" type="number" required placeholder="25" className={input}/><input name="maxScore" type="number" required placeholder="30" className={input}/><button className={`${submit} col-span-3`}>添加等级区间</button></form></Rule><Rule title="九宫格规则"><form action={addTalentNineBoxRule} className="grid grid-cols-3 gap-2">{draftSelect()}<input name="code" required placeholder="HIGH_HIGH" className={input}/><input name="label" required placeholder="高潜高绩" className={input}/><input name="potentialMin" type="number" required placeholder="8" className={input}/><input name="potentialMax" type="number" required placeholder="10" className={input}/><input name="performanceMin" type="number" required placeholder="8" className={input}/><input name="performanceMax" type="number" required placeholder="10" className={input}/><input name="colorToken" required defaultValue="success" className={input}/><button className={submit}>添加九宫格</button></form></Rule></div></Card>}
    <div className="space-y-4">{data.templates.map((template) => { const dimensions = data.dimensions.filter((row) => row.templateVersionId === template.id); const ratings = data.ratings.filter((row) => row.templateVersionId === template.id); const thresholds = data.thresholds.filter((row) => row.templateVersionId === template.id); const boxes = data.nineBoxRules.filter((row) => row.templateVersionId === template.id); return <Card key={template.id}><div className="flex justify-between"><div><h3 className="font-semibold">{template.name} V{template.version}</h3><p className="text-xs text-muted-foreground">{departmentName.get(template.departmentOrgNodeId)} · {template.code}</p></div><Badge tone={template.status === "ACTIVE" ? "success" : "warning"}>{template.status}</Badge></div><div className="grid grid-cols-4 gap-3 my-4 text-center">{[["维度", dimensions.length],["评分档",ratings.length],["等级",thresholds.length],["九宫格",boxes.length]].map(([label,count]) => <div key={String(label)} className="rounded-xl bg-muted/50 p-3"><div className="text-xs text-muted-foreground">{label}</div><b>{count}</b></div>)}</div>{template.status === "DRAFT" && <div className="flex justify-end gap-2"><form action={initializeDefaultTalentReviewTemplate}><input type="hidden" name="templateVersionId" value={template.id}/><button className="h-8 rounded-full border px-3 text-xs">初始化六维默认规则</button></form><form action={publishTalentReviewTemplate}><input type="hidden" name="id" value={template.id}/><button className="h-8 rounded-full bg-primary px-3 text-xs text-primary-foreground">校验并发布</button></form></div>}</Card>; })}</div>
  </Card>;
}
function Rule({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-xl border border-border p-3"><h4 className="text-sm font-medium mb-3">{title}</h4>{children}</div>; }
