/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueTrackingRouteImport } from './routes/value-tracking'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as QuarterlyWorkRouteImport } from './routes/quarterly-work'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KpiRouteImport } from './routes/kpi'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AnnualGoalsRouteImport } from './routes/annual-goals'
import { Route as IndexRouteImport } from './routes/index'

const ValueTrackingRoute = ValueTrackingRouteImport.update({
  id: '/value-tracking',
  path: '/value-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const QuarterlyWorkRoute = QuarterlyWorkRouteImport.update({
  id: '/quarterly-work',
  path: '/quarterly-work',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiRoute = KpiRouteImport.update({
  id: '/kpi',
  path: '/kpi',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualGoalsRoute = AnnualGoalsRouteImport.update({
  id: '/annual-goals',
  path: '/annual-goals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annual-goals': typeof AnnualGoalsRoute
  '/dashboard': typeof DashboardRoute
  '/kpi': typeof KpiRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/quarterly-work': typeof QuarterlyWorkRoute
  '/talent': typeof TalentRoute
  '/todos': typeof TodosRoute
  '/value-tracking': typeof ValueTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annual-goals': typeof AnnualGoalsRoute
  '/dashboard': typeof DashboardRoute
  '/kpi': typeof KpiRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/quarterly-work': typeof QuarterlyWorkRoute
  '/talent': typeof TalentRoute
  '/todos': typeof TodosRoute
  '/value-tracking': typeof ValueTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annual-goals': typeof AnnualGoalsRoute
  '/dashboard': typeof DashboardRoute
  '/kpi': typeof KpiRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/organization': typeof OrganizationRoute
  '/quarterly-work': typeof QuarterlyWorkRoute
  '/talent': typeof TalentRoute
  '/todos': typeof TodosRoute
  '/value-tracking': typeof ValueTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annual-goals'
    | '/dashboard'
    | '/kpi'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/quarterly-work'
    | '/talent'
    | '/todos'
    | '/value-tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/annual-goals'
    | '/dashboard'
    | '/kpi'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/quarterly-work'
    | '/talent'
    | '/todos'
    | '/value-tracking'
  id:
    | '__root__'
    | '/'
    | '/annual-goals'
    | '/dashboard'
    | '/kpi'
    | '/login'
    | '/notifications'
    | '/organization'
    | '/quarterly-work'
    | '/talent'
    | '/todos'
    | '/value-tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnualGoalsRoute: typeof AnnualGoalsRoute
  DashboardRoute: typeof DashboardRoute
  KpiRoute: typeof KpiRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OrganizationRoute: typeof OrganizationRoute
  QuarterlyWorkRoute: typeof QuarterlyWorkRoute
  TalentRoute: typeof TalentRoute
  TodosRoute: typeof TodosRoute
  ValueTrackingRoute: typeof ValueTrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value-tracking': {
      id: '/value-tracking'
      path: '/value-tracking'
      fullPath: '/value-tracking'
      preLoaderRoute: typeof ValueTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quarterly-work': {
      id: '/quarterly-work'
      path: '/quarterly-work'
      fullPath: '/quarterly-work'
      preLoaderRoute: typeof QuarterlyWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi': {
      id: '/kpi'
      path: '/kpi'
      fullPath: '/kpi'
      preLoaderRoute: typeof KpiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual-goals': {
      id: '/annual-goals'
      path: '/annual-goals'
      fullPath: '/annual-goals'
      preLoaderRoute: typeof AnnualGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnualGoalsRoute: AnnualGoalsRoute,
  DashboardRoute: DashboardRoute,
  KpiRoute: KpiRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OrganizationRoute: OrganizationRoute,
  QuarterlyWorkRoute: QuarterlyWorkRoute,
  TalentRoute: TalentRoute,
  TodosRoute: TodosRoute,
  ValueTrackingRoute: ValueTrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
