import Link from "next/link";
import { redirect } from "next/navigation";
import { Badge, Card, PageHeader } from "@/components/ui-kit";
import { requireCurrentUser } from "@/server/auth/current-user";
import { addBusinessAssessmentSubject, createBusinessAssessmentCycle, importBusinessAssessmentResults } from "@/server/talent/assessment-actions";
import { getBusinessAssessmentPageData } from "@/server/talent/assessment-query";

const input = "h-9 rounded-lg border border-border bg-background px-3 text-sm";
const labels: Record<string, string> = { DRAFT: "草稿", CONFIRMED: "已确认", FAILED: "预检失败", INITIAL_PASS: "首次及格", RETEST_PASS: "补考及格", FINAL_FAIL: "最终不及格" };

export default async function BusinessAssessmentPage() {
  redirect("/talent?section=assessment");
  const user = await requireCurrentUser(); const data = await getBusinessAssessmentPageData(user); const userName = new Map(data.users.map((row) => [row.id, row.name]));
  return <Card className="!p-6">
    <PageHeader title="业务考核" description="只保存最终结果；6分按科目均摊，首次及格满分、补考及格半分、最终不及格0分" action={<Link href="/talent" className="flex h-9 items-center rounded-full border border-border px-4 text-sm">返回人才发展</Link>} />
    {data.canManage ? <div className="grid gap-4 lg:grid-cols-2">
      <Card><h3 className="mb-3 font-semibold">创建考核批次</h3><form action={createBusinessAssessmentCycle} className="grid gap-2 sm:grid-cols-2"><select name="departmentOrgNodeId" required className={input}>{data.departments.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input name="name" required placeholder="批次名称" className={input}/><input name="year" type="number" defaultValue={new Date().getFullYear()} className={input}/><select name="quarter" className={input}>{[1,2,3,4].map((q) => <option key={q} value={q}>Q{q}</option>)}</select><button className="sm:col-span-2 h-9 rounded-full bg-primary text-primary-foreground">创建6分制批次</button></form></Card>
      <Card><h3 className="mb-3 font-semibold">配置科目</h3><form action={addBusinessAssessmentSubject} className="grid gap-2 sm:grid-cols-2"><select name="cycleId" required className={input}>{data.cycles.filter((row) => row.status === "DRAFT").map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input name="code" required placeholder="科目编码" className={input}/><input name="name" required placeholder="科目名称" className={input}/><select name="scoringType" className={input}><option value="NUMERIC">分数评分</option><option value="GRADE">等级评分</option></select><input name="passingNumericScore" defaultValue="80" placeholder="及格分" className={input}/><select name="requiredGradeCode" className={input}>{["S","A","B","C","D"].map((grade) => <option key={grade} value={grade}>要求 {grade} 级</option>)}</select><input name="sortOrder" type="number" defaultValue="10" className={input}/><button className="h-9 rounded-full bg-primary text-primary-foreground">新增并重新摊分</button></form></Card>
    </div> : null}
    {data.canManage ? <Card className="mt-4"><div className="mb-3"><h3 className="font-semibold">导入最终结果</h3><p className="mt-1 text-xs text-muted-foreground">表头：姓名、科目名称、最终值、最终结果、考核开始日期、考核结束日期、备注。最终结果支持“首次及格/补考及格/补考不及格”。整批预检通过后才写入。</p></div><form action={importBusinessAssessmentResults} className="flex flex-wrap gap-2"><select name="cycleId" required className={`${input} min-w-60`}>{data.cycles.filter((row) => row.status === "DRAFT").map((row) => <option key={row.id} value={row.id}>{row.year} Q{row.quarter} · {row.name}</option>)}</select><input name="file" type="file" accept=".xlsx,.xls,.csv" required className={`${input} h-auto py-1.5 flex-1`}/><button className="h-9 rounded-full bg-primary px-5 text-sm text-primary-foreground">预检并导入</button></form></Card> : null}
    <Card className="mt-4 !p-0 overflow-hidden"><table className="w-full text-sm"><thead className="bg-muted/40"><tr>{["批次","科目与摊分","员工结果","状态"].map((item) => <th key={item} className="p-4 text-left text-xs font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-border">{data.cycles.map((cycle) => { const subjects = data.subjects.filter((row) => row.cycleId === cycle.id); const summaries = data.summaries.filter((row) => row.cycleId === cycle.id); return <tr key={cycle.id}><td className="p-4 font-medium">{cycle.name}<div className="text-xs text-muted-foreground">{cycle.year} Q{cycle.quarter} · 总分6</div></td><td className="p-4 text-xs">{subjects.length ? subjects.map((row) => `${row.name} ${row.maxScore ?? 0}分`).join("、") : "待配置"}</td><td className="p-4"><div className="space-y-1">{summaries.slice(0,5).map((row) => <div key={row.id} className="text-xs">{userName.get(row.userId) ?? row.userId}：{row.earnedScore}/{row.maxScore}</div>)}{summaries.length > 5 ? <div className="text-xs text-muted-foreground">共 {summaries.length} 人</div> : null}</div></td><td className="p-4"><Badge tone={cycle.status === "CONFIRMED" ? "success" : "warning"}>{labels[cycle.status] ?? cycle.status}</Badge></td></tr>; })}</tbody></table>{data.cycles.length === 0 ? <div className="py-10 text-center text-sm text-muted-foreground">暂无业务考核批次</div> : null}</Card>
  </Card>;
}
