import Link from "next/link";
import { Badge, Card, PageHeader } from "@/components/ui-kit";
import { requireCurrentUser } from "@/server/auth/current-user";
import { createWorkIncident, voidWorkIncident } from "@/server/talent/incident-actions";
import { getWorkIncidentPageData } from "@/server/talent/incident-query";

const input = "h-9 rounded-lg border border-border bg-background px-3 text-sm";
export default async function WorkIncidentsPage() {
  const user = await requireCurrentUser(); const data = await getWorkIncidentPageData(user); const userName = new Map(data.users.map((row) => [row.id, row.name])); const peopleByIncident = new Map(data.responsiblePeople.map((row) => [row.incidentId, row]));
  return <Card className="!p-6"><PageHeader title="工作事故" description="维护已确认事实、事故等级和限制期；KPI只实时查询扣分结果" action={<Link href="/talent" className="flex h-9 items-center rounded-full border border-border px-4 text-sm">返回人才发展</Link>}/>
    {data.canManage ? <Card className="mb-4"><h3 className="mb-3 font-semibold">录入并确认工作事故</h3><form action={createWorkIncident} className="grid gap-2 md:grid-cols-4"><select name="departmentOrgNodeId" required className={input}>{data.departments.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><select name="userId" required className={input}>{data.users.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select><input name="incidentNo" required placeholder="事故编号" className={input}/><input name="occurredAt" type="date" required className={input}/><select name="level" className={input}>{["S","A","B","C","D"].map((level) => <option key={level} value={level}>{level}级</option>)}</select><input name="title" required placeholder="事故标题" className={`${input} md:col-span-2`}/><input name="externalReferenceNo" placeholder="公司制度/外部单号（可选）" className={input}/><textarea name="description" required placeholder="已确认事实和事故说明" className="min-h-20 rounded-lg border border-border bg-background p-3 text-sm md:col-span-3"/><button className="rounded-full bg-primary px-5 text-sm text-primary-foreground">保存并确认</button></form></Card> : null}
    <Card className="!p-0 overflow-hidden"><table className="w-full text-sm"><thead className="bg-muted/40"><tr>{["日期/编号","责任人","等级","事故摘要","季度KPI结果","状态/操作"].map((item) => <th key={item} className="p-4 text-left text-xs font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-border">{data.incidents.map((incident) => { const person = peopleByIncident.get(incident.id); const period = { year: incident.occurredAt.getFullYear(), quarter: Math.floor(incident.occurredAt.getMonth()/3)+1 }; const summary = data.summaries.find((row) => row.userId === person?.userId && row.year === period.year && row.quarter === period.quarter); return <tr key={incident.id}><td className="p-4 text-xs">{incident.occurredAt.toLocaleDateString("zh-CN")}<div className="text-muted-foreground">{incident.incidentNo}</div></td><td className="p-4 font-medium">{person ? userName.get(person.userId) ?? person.userId : "—"}</td><td className="p-4"><Badge tone={["S","A","B"].includes(incident.level) ? "danger" : "warning"}>{incident.level}级</Badge></td><td className="p-4"><div>{incident.title}</div><div className="mt-1 max-w-md text-xs text-muted-foreground">{incident.description}</div></td><td className="p-4 text-xs">{summary ? `工作事故项扣 ${Math.abs(summary.kpiPenalty)} 分` : "—"}</td><td className="p-4"><Badge tone={incident.status === "CONFIRMED" ? "success" : "default"}>{incident.status === "CONFIRMED" ? "已确认" : "已作废"}</Badge>{data.canManage && incident.status === "CONFIRMED" ? <form action={voidWorkIncident} className="mt-2 flex gap-1"><input type="hidden" name="id" value={incident.id}/><input name="voidReason" required placeholder="作废原因" className="h-7 w-28 rounded border border-border px-2 text-xs"/><button className="text-xs text-destructive">作废</button></form> : null}</td></tr>; })}</tbody></table>{data.incidents.length === 0 ? <div className="py-10 text-center text-sm text-muted-foreground">暂无工作事故</div> : null}</Card>
  </Card>;
}
