import Link from "next/link";
import { notFound } from "next/navigation";
import { Badge, Card, PageHeader } from "@/components/ui-kit";
import { requireCurrentUser } from "@/server/auth/current-user";
import { calibrateTalentReviewResult, confirmTalentReviewCycle, saveTalentReviewEvaluation } from "@/server/talent/review-actions";
import { getTalentReviewCycleDetail } from "@/server/talent/review-query";

const selectClass = "h-9 rounded-lg border border-border bg-background px-3 text-sm";
export default async function Page({ params }: { params: Promise<{ cycleId: string }> }) {
  const user = await requireCurrentUser(); const data = await getTalentReviewCycleDetail(user, (await params).cycleId); if (!data) notFound();
  const userById = new Map(data.users.map((row) => [row.id, row])); const resultById = new Map(data.results.map((row) => [row.participantId, row])); const ratingByKey = new Map(data.dimensionResults.map((row) => [`${row.participantId}:${row.dimensionId}`, row.ratingCode]));
  const editable = (data.cycle.status === "IN_PROGRESS" || data.cycle.status === "CALIBRATING") && data.canManage;
  return <Card className="!p-6"><PageHeader title={data.cycle.name} description={`${data.cycle.year}年${data.cycle.halfYear === 1 ? "上半年" : "下半年"} · ${data.template?.name} · ${data.cycle.status}`} action={<div className="flex gap-2"><Link href="/talent/reviews" className="h-9 rounded-full border border-border px-4 text-sm flex items-center">返回批次</Link>{editable && data.canCalibrate && <form action={confirmTalentReviewCycle}><input type="hidden" name="cycleId" value={data.cycle.id}/><button className="h-9 rounded-full bg-primary px-4 text-sm text-primary-foreground">确认全部结果</button></form>}</div>}/>
    <div className="space-y-4">{data.participants.map((participant) => { const person = userById.get(participant.userId); const result = resultById.get(participant.id); return <Card key={participant.id}><div className="flex justify-between"><div><h3 className="font-semibold">{person?.name}</h3><p className="text-xs text-muted-foreground">{person?.title ?? "未配置岗位"} · 组织/岗位/职级快照已冻结</p></div>{result ? <div className="text-right"><b>{result.totalScore} 分</b><div><Badge tone="success">{result.gradeCode} · {result.talentType}</Badge></div></div> : <Badge>待评价</Badge>}</div>
      {editable && <form action={saveTalentReviewEvaluation} className="mt-4"><input type="hidden" name="participantId" value={participant.id}/><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{data.dimensions.map((dimension) => <label key={dimension.id} className="rounded-xl border border-border p-3"><span className="block text-xs mb-2">{dimension.name}</span><select name={`rating_${dimension.id}`} defaultValue={ratingByKey.get(`${participant.id}:${dimension.id}`) ?? "B"} className={`w-full ${selectClass}`}>{data.ratings.map((rating) => <option key={rating.id} value={rating.code}>{rating.code} · {rating.label} · {rating.numericScore}分</option>)}</select></label>)}</div><div className="mt-3 flex gap-2"><input name="managerComment" defaultValue={result?.managerComment ?? ""} placeholder="评价说明" className="flex-1 h-9 rounded-lg border border-border px-3 text-sm"/><button className="h-9 rounded-full bg-primary px-4 text-sm text-primary-foreground">保存并计算</button></div></form>}
      {result && editable && data.canCalibrate && <form action={calibrateTalentReviewResult} className="mt-3 border-t border-border pt-3 grid md:grid-cols-4 gap-2"><input type="hidden" name="participantId" value={participant.id}/><select name="gradeCode" defaultValue={result.gradeCode} className={selectClass}>{data.thresholds.map((row) => <option key={row.id} value={row.gradeCode}>{row.gradeCode} · {row.label}</option>)}</select><select name="nineBoxCode" defaultValue={result.nineBoxCode ?? ""} className={selectClass}>{data.nineBoxRules.map((row) => <option key={row.id} value={row.code}>{row.label}</option>)}</select><input name="managerComment" defaultValue={result.managerComment ?? ""} placeholder="校准说明" className={selectClass}/><button className="h-9 rounded-full border border-primary text-sm text-primary">保存校准</button></form>}
    </Card>; })}</div>
  </Card>;
}
