-- Migration-history placeholder for the KPI permission rollout.
-- On main, 20260717170000_org_permission_subject_type creates the complete
-- OrgPermissionGrant target table for a fresh database. Existing db-pushed
-- databases are normalized before both migrations are marked as applied.
